repos:
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
        files: ^src/.*\.py$
        args: ["--config=.flake8"]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort
        files: ^src/.*\.py$
        args: ["--settings-file=pyproject.toml"]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        files: ^src/.*\.py$
        args: ["--config=pyproject.toml"]
