"""initial

Revision ID: 7530c6b4a018
Revises:
Create Date: 2025-01-11 16:08:46.322634

"""
import clickhouse_sqlalchemy
import sqlalchemy as sa
from alembic import op
from clickhouse_sqlalchemy import engines

# revision identifiers, used by Alembic.
revision = "7530c6b4a018"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column("query", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column(
            "method", clickhouse_sqlalchemy.types.common.String(), nullable=False
        ),
        sa.Column("ip", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column(
            "user_agent", clickhouse_sqlalchemy.types.common.String(), nullable=False
        ),
        sa.Column(
            "created_at", clickhouse_sqlalchemy.types.common.DateTime(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        engines.MergeTree(
            primary_key=["id"],
            order_by=["id", "created_at"],
        ),
    )  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analytics")
    # ### end Alembic commands ###
