"""initial

Revision ID: f8c12039e3df
Revises:
Create Date: 2024-12-27 15:47:48.643736

"""
import clickhouse_sqlalchemy
import sqlalchemy as sa
from alembic import op
from clickhouse_sqlalchemy import engines

# revision identifiers, used by Alembic.
revision = "f8c12039e3df"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column("title", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column(
            "content", clickhouse_sqlalchemy.types.common.String(), nullable=False
        ),
        sa.Column("type", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column(
            "file_format", clickhouse_sqlalchemy.types.common.String(), nullable=False
        ),
        sa.Column("size", clickhouse_sqlalchemy.types.common.Int32(), nullable=False),
        sa.Column(
            "created_at", clickhouse_sqlalchemy.types.common.DateTime(), nullable=False
        ),
        sa.PrimaryKeyConstraint("title", "file_format", "type", "size"),
        engines.ReplacingMergeTree(
            primary_key=["title", "file_format", "type", "size"],
            order_by=["title", "file_format", "type", "size", "created_at"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document")
    # ### end Alembic commands ###
